<?php

namespace Database\Seeders;

use App\Models\Plate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plates = [
            // Piatti americani, restaurant_id 1
            [
                "restaurant_id" => 1,
                "name" => "Hamburger",
                "description" => "Panino di carne macinata di manzo cotto alla griglia, servito con insalata, pomodoro e salse varie.",
                "price" => 12.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 1,
                "name" => "Hot dog",
                "description" => "Salsiccia cotta alla griglia servita su un panino morbido, guarnito con senape, ketchup, cipolle e cetriolini.",
                "price" => 8.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 1,
                "name" => "Mac and cheese",
                "description" => "Pasta cotta al dente con una salsa cremosa di formaggio fuso, servita calda e filante.",
                "price" => 9.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 1,
                "name" => "BBQ ribs",
                "description" => "Costine di maiale cotte a fuoco lento e glassate con salsa barbecue, servite con patatine fritte e insalata.",
                "price" => 18.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 1,
                "name" => "Fried chicken",
                "description" => "Pollo fritto croccante e succoso, servito con patatine fritte e salse varie.",
                "price" => 14.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 1,
                "name" => "Buffalo wings",
                "description" => "Ali di pollo croccanti servite con salsa piccante al burro di buffalo e bastoncini di sedano.",
                "price" => 10.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 1,
                "name" => "Taco salad",
                "description" => "Insalata di lattuga, pomodoro, cipolla, fagioli, formaggio e carne di manzo speziata servita in una conchiglia di tortilla croccante.",
                "price" => 13.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            // Piatti giapponesi, restaurant_id 2
            [
                "restaurant_id" => 2,
                "name" => "Sushi",
                "description" => "Piatto di pesce crudo su una base di riso condito con aceto di riso, servito con salsa di soia, wasabi e zenzero marinato.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 2,
                "name" => "Ramen",
                "description" => "Brodo di carne o pesce con noodles di frumento, carne di maiale o pollo, uovo sodo, germogli di soia e cipolla verde.",
                "price" => 12.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 2,
                "name" => "Tempura",
                "description" => "Frittura di gamberi, verdure e pesce ricoperti di pastella leggera, serviti con salsa di immersione.",
                "price" => 14.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 2,
                "name" => "Yakitori",
                "description" => "Spiedini di pollo o manzo marinati e grigliati, serviti con salsa teriyaki.",
                "price" => 9.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 2,
                "name" => "Udon",
                "description" => "Zuppa di noodles spessi di frumento, servita con gamberi, verdure, pollo e uova.",
                "price" => 11.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 2,
                "name" => "Onigiri",
                "description" => "Palline di riso ripiene di pesce, verdure o uova, condite con salsa di soia e alga nori.",
                "price" => 5.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ], [

                "restaurant_id" => 2,
                "name" => "Soba",
                "description" => "Zuppa di noodles di grano saraceno, servita con verdure, uova e tofu.",
                "price" => 13.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,

            ],
            // Piatti cinesi, restaurant_id 3
            [
                "restaurant_id" => 3,
                "name" => "Ravioli cinesi",
                "description" => "Pasta ripiena di carne di maiale e verdure, cotta al vapore o in brodo, servita con salsa di soia e aceto di riso.",
                "price" => 10.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 3,
                "name" => "Ma po tofu",
                "description" => "Tofu morbido in una salsa piccante di carne di maiale e fagioli fermentati, servito con riso bianco.",
                "price" => 12.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 3,
                "name" => "Pollo alle mandorle",
                "description" => "Pollo fritto croccante con mandorle tostate, servito con verdure saltate in padella.",
                "price" => 14.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 3,
                "name" => "Anatra alla pechinese",
                "description" => "Anatra arrosto con croccante pelle dorata, servita con pancake sottili, cipolla e salsa di prugne.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 3,
                "name" => "Zuppa di noodle",
                "description" => "Zuppa di noodles di frumento con pollo, verdure e funghi, arricchita con uovo sodo e cipolla verde.",
                "price" => 9.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 3,
                "name" => "Gamberi saltati con peperoncino",
                "description" => "Gamberi freschi saltati in padella con peperoncino, aglio, salvia e prezzemolo, serviti con riso bianco.",
                "price" => 15.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 3,
                "name" => "Agrodolce di verdure",
                "description" => "Verdure miste in agrodolce di aceto, zucchero e salsa di soia, servite con riso basmati.",
                "price" => 11.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,

            ],
            // Piatti indiani, restaurant_id 4
            [
                "restaurant_id" => 4,
                "name" => "Pollo tikka masala",
                "description" => "Pollo marinato e grigliato, servito in una salsa cremosa di pomodoro, cipolla e spezie, accompagnato da riso basmati.",
                "price" => 13.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 4,
                "name" => "Paneer makhani",
                "description" => "Cubetti di paneer (formaggio indiano) cotto in una salsa cremosa di pomodoro e burro, servito con riso basmati o naan.",
                "price" => 11.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 4,
                "name" => "Samosa",
                "description" => "Fagottini di pasta ripieni di patate, piselli, cipolla e spezie, fritti croccanti e serviti con chutney.",
                "price" => 6.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 4,
                "name" => "Biryani di agnello",
                "description" => "Riso basmati cotto con spezie, agnello e verdure, servito con raita (salsa di yogurt) e papadum (sfoglia croccante di lenticchie).",
                "price" => 15.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 4,
                "name" => "Butter chicken",
                "description" => "Pollo cotto in una salsa di pomodoro e burro, arricchita con spezie indiane e servita con riso basmati o naan.",
                "price" => 12.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 4,
                "name" => "Chana masala",
                "description" => "Ceci cotti in una salsa speziata di pomodoro e cipolla, serviti con riso basmati o naan.",
                "price" => 10.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,
            ], [
                "restaurant_id" => 4,
                "name" => "Aloo gobi",
                "description" => "Patate e cavolfiore cucinati con spezie indiane e serviti con riso basmati o naan.",
                "price" => 10.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,

            ],
            // Piatti messicani, restaurant_id 5
            [
                "restaurant_id" => 5,
                "name" => "Tacos al pastor",
                "description" => "Tortilla di mais ripiena di carne di maiale marinata e cotta allo spiedo, servita con cipolla, coriandolo e salsa piccante.",
                "price" => 8.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 5,
                "name" => "Guacamole",
                "description" => "Salsa di avocado, pomodoro, cipolla, peperoncino e lime, servita con tortilla chips.",
                "price" => 5.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 5,
                "name" => "Burrito",
                "description" => "Tortilla di farina ripiena di carne di manzo, riso, fagioli, salsa di pomodoro, guacamole e formaggio, servita con pico de gallo.",
                "price" => 10.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 5,
                "name" => "Enchiladas",
                "description" => "Tortilla di mais ripiena di pollo, formaggio e salsa di pomodoro, servita con fagioli e riso.",
                "price" => 9.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 5,
                "name" => "Chiles en nogada",
                "description" => "Peperoni verdi ripieni di carne macinata, frutta secca e spezie, serviti con una salsa di panna, noci e prezzemolo.",
                "price" => 12.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 5,
                "name" => "Quesadillas",
                "description" => "Tortilla di mais ripiena di formaggio fuso e pollo, servita con guacamole e pico de gallo.",
                "price" => 8.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 5,
                "name" => "Fajitas",
                "description" => "Strisce di carne di manzo o pollo, peperoni e cipolle saltati in padella e serviti su tortilla di farina, con pico de gallo, guacamole e formaggio.",
                "price" => 11.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            // Piatti polacchi, restaurant_id 6
            [
                "restaurant_id" => 6,
                "name" => "Pierogi",
                "description" => "Pasta ripiena di patate, formaggio o carne, cotta e servita con cipolle saltate e panna acida.",
                "price" => 7.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 6,
                "name" => "Bigos",
                "description" => "Stufato di carne di maiale, salsiccia, crauti e funghi, condito con spezie e servito con pane di segale.",
                "price" => 9.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 6,
                "name" => "Zurek",
                "description" => "Zuppa acida a base di farina di segale, servita con salsicce, uova sode e patate.",
                "price" => 6.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 6,
                "name" => "Kotlet schabowy",
                "description" => "Cotoletta di maiale impanata, servita con patate bollite e crauti.",
                "price" => 11.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 6,
                "name" => "Kielbasa",
                "description" => "Salsiccia polacca affumicata, servita con senape e pane di segale.",
                "price" => 8.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 6,
                "name" => "Barszcz",
                "description" => "Zuppa rossa a base di barbabietole, servita con uova sode, pancetta affumicata e crema acida.",
                "price" => 6.95,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ], [
                "restaurant_id" => 6,
                "name" => "Gołąbki",
                "description" => "Involtini di verza ripieni di carne macinata, riso e verdure, serviti con salsa di pomodoro.",
                "price" => 10.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            // Piatti italiani, restaurant_id 7
            [
                "restaurant_id" => 7,
                "name" => "Spaghetti alla Carbonara",
                "description" => "Uno dei piatti più famosi della cucina romana, preparato con spaghetti, uova, guanciale e pecorino romano.",
                "price" => 12.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 7,
                "name" => "Pizza Margherita",
                "description" => "La pizza più classica e famosa, preparata con mozzarella di bufala, pomodoro e basilico.",
                "price" => 8.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 7,
                "name" => "Risotto alla Milanese",
                "description" => "Un piatto tipico della cucina lombarda, preparato con riso, burro, cipolla e zafferano.",
                "price" => 15.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 7,
                "name" => "Osso Buco alla Milanese",
                "description" => "Un piatto a base di carne di vitello, preparato con osso con midollo, verdure e vino bianco.",
                "price" => 20.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 7,
                "name" => "Lasagne alla Bolognese",
                "description" => "Un piatto di pasta al forno, preparato con sfoglia di pasta fresca, ragù di carne, besciamella e parmigiano reggiano.",
                "price" => 16.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 7,
                "name" => "Cacio e Pepe",
                "description" => "Un altro piatto tradizionale romano, preparato con spaghetti, pecorino romano e pepe nero.",
                "price" => 11.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 7,
                "name" => "Parmigiana di Melanzane",
                "description" => "Una deliziosa pietanza tipica del Sud Italia, preparata con melanzane fritte, sugo di pomodoro, mozzarella e parmigiano reggiano gratinato.",
                "price" => 14.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Piatti ristorante italiano id 8
            [
                "restaurant_id" => 8,
                "name" => "Tagliatelle al Ragù",
                "description" => "Una ricetta della tradizione bolognese, con tagliatelle fatte in casa e condite con un saporito ragù di carne.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 8,
                "name" => "Pollo alla Cacciatora",
                "description" => "Un piatto tipico della cucina toscana, preparato con pollo, pomodori, olive, cipolla e peperoncino.",
                "price" => 19.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 8,
                "name" => "Filetto di Branzino al Cartoccio",
                "description" => "Un gustoso piatto di pesce, preparato con filetto di branzino fresco, verdure e spezie, cottura a vapore in carta forno.",
                "price" => 23.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 8,
                "name" => "Insalata Caprese",
                "description" => "Un'insalata fresca e colorata, ideale come antipasto o contorno, con pomodori, mozzarella di bufala e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 8,
                "name" => "Tiramisù",
                "description" => "Un dolce italiano classico, preparato con savoiardi, caffè, mascarpone e cacao.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 8,
                "name" => "Panna Cotta",
                "description" => "Un dolce delicato e cremoso, preparato con panna, gelatina, zucchero e vaniglia.",
                "price" => 6.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 8,
                "name" => "Croccante alle Mandorle",
                "description" => "Un dolce croccante e goloso, preparato con mandorle tostate, zucchero e miele.",
                "price" => 8.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante italiano id 9
            [
                "restaurant_id" => 9,
                "name" => "Pizza Margherita",
                "description" => "La pizza classica napoletana, con pomodoro, mozzarella e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 9,
                "name" => "Spaghetti alla Carbonara",
                "description" => "Una ricetta romana, con spaghetti, uovo, pancetta e pecorino romano.",
                "price" => 14.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 9,
                "name" => "Melanzane alla Parmigiana",
                "description" => "Un piatto vegetariano tipico del sud Italia, preparato con melanzane, pomodoro e parmigiano.",
                "price" => 12.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 9,
                "name" => "Bistecca alla Fiorentina",
                "description" => "Un piatto della tradizione toscana, con una succulenta bistecca di manzo grigliata.",
                "price" => 22.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 9,
                "name" => "Ravioli di Ricotta",
                "description" => "Un piatto di pasta fresca, ripieno di ricotta e spinaci e condito con burro e salvia.",
                "price" => 16.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 9,
                "name" => "Torta della Nonna",
                "description" => "Un dolce tradizionale della cucina toscana, preparato con pasta frolla, crema pasticcera e pinoli.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 9,
                "name" => "Salmone alla Griglia",
                "description" => "Un piatto semplice e gustoso, con un filetto di salmone cotto alla griglia con un filo di olio evo.",
                "price" => 20.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            // Ristorante italiano e giapponese id 10
            [
                "restaurant_id" => 10,
                "name" => "Tagliatelle al Ragù",
                "description" => "Una ricetta della tradizione bolognese, con tagliatelle fatte in casa e condite con un saporito ragù di carne.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 10,
                "name" => "Pollo alla Cacciatora",
                "description" => "Un piatto tipico della cucina toscana, preparato con pollo, pomodori, olive, cipolla e peperoncino.",
                "price" => 19.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 10,
                "name" => "Filetto di Branzino al Cartoccio",
                "description" => "Un gustoso piatto di pesce, preparato con filetto di branzino fresco, verdure e spezie, cottura a vapore in carta forno.",
                "price" => 23.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 10,
                "name" => "Insalata Caprese",
                "description" => "Un'insalata fresca e colorata, ideale come antipasto o contorno, con pomodori, mozzarella di bufala e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 10,
                "name" => "Tiramisù",
                "description" => "Un dolce italiano classico, preparato con savoiardi, caffè, mascarpone e cacao.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 10,
                "name" => "Panna Cotta",
                "description" => "Un dolce delicato e cremoso, preparato con panna, gelatina, zucchero e vaniglia.",
                "price" => 6.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 10,
                "name" => "Croccante alle Mandorle",
                "description" => "Un dolce croccante e goloso, preparato con mandorle tostate, zucchero e miele.",
                "price" => 8.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante italiano e americano id 11
            [
                "restaurant_id" => 11,
                "name" => "Tagliatelle al Ragù",
                "description" => "Una ricetta della tradizione bolognese, con tagliatelle fatte in casa e condite con un saporito ragù di carne.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 11,
                "name" => "Pollo alla Cacciatora",
                "description" => "Un piatto tipico della cucina toscana, preparato con pollo, pomodori, olive, cipolla e peperoncino.",
                "price" => 19.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 11,
                "name" => "Filetto di Branzino al Cartoccio",
                "description" => "Un gustoso piatto di pesce, preparato con filetto di branzino fresco, verdure e spezie, cottura a vapore in carta forno.",
                "price" => 23.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 11,
                "name" => "Insalata Caprese",
                "description" => "Un'insalata fresca e colorata, ideale come antipasto o contorno, con pomodori, mozzarella di bufala e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 11,
                "name" => "Tiramisù",
                "description" => "Un dolce italiano classico, preparato con savoiardi, caffè, mascarpone e cacao.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 11,
                "name" => "Panna Cotta",
                "description" => "Un dolce delicato e cremoso, preparato con panna, gelatina, zucchero e vaniglia.",
                "price" => 6.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 11,
                "name" => "Croccante alle Mandorle",
                "description" => "Un dolce croccante e goloso, preparato con mandorle tostate, zucchero e miele.",
                "price" => 8.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante cinese e giappone id 12
            [
                "restaurant_id" => 12,
                "name" => "Pizza Margherita",
                "description" => "La pizza classica napoletana, con pomodoro, mozzarella e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 12,
                "name" => "Spaghetti alla Carbonara",
                "description" => "Una ricetta romana, con spaghetti, uovo, pancetta e pecorino romano.",
                "price" => 14.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 12,
                "name" => "Melanzane alla Parmigiana",
                "description" => "Un piatto vegetariano tipico del sud Italia, preparato con melanzane, pomodoro e parmigiano.",
                "price" => 12.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 12,
                "name" => "Bistecca alla Fiorentina",
                "description" => "Un piatto della tradizione toscana, con una succulenta bistecca di manzo grigliata.",
                "price" => 22.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 12,
                "name" => "Ravioli di Ricotta",
                "description" => "Un piatto di pasta fresca, ripieno di ricotta e spinaci e condito con burro e salvia.",
                "price" => 16.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 12,
                "name" => "Torta della Nonna",
                "description" => "Un dolce tradizionale della cucina toscana, preparato con pasta frolla, crema pasticcera e pinoli.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 12,
                "name" => "Salmone alla Griglia",
                "description" => "Un piatto semplice e gustoso, con un filetto di salmone cotto alla griglia con un filo di olio evo.",
                "price" => 20.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            // Ristorante italiano e messicano id 13
            [
                "restaurant_id" => 13,
                "name" => "Tagliatelle al Ragù",
                "description" => "Una ricetta della tradizione bolognese, con tagliatelle fatte in casa e condite con un saporito ragù di carne.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 13,
                "name" => "Pollo alla Cacciatora",
                "description" => "Un piatto tipico della cucina toscana, preparato con pollo, pomodori, olive, cipolla e peperoncino.",
                "price" => 19.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 13,
                "name" => "Filetto di Branzino al Cartoccio",
                "description" => "Un gustoso piatto di pesce, preparato con filetto di branzino fresco, verdure e spezie, cottura a vapore in carta forno.",
                "price" => 23.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 13,
                "name" => "Insalata Caprese",
                "description" => "Un'insalata fresca e colorata, ideale come antipasto o contorno, con pomodori, mozzarella di bufala e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 13,
                "name" => "Tiramisù",
                "description" => "Un dolce italiano classico, preparato con savoiardi, caffè, mascarpone e cacao.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 13,
                "name" => "Panna Cotta",
                "description" => "Un dolce delicato e cremoso, preparato con panna, gelatina, zucchero e vaniglia.",
                "price" => 6.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 13,
                "name" => "Croccante alle Mandorle",
                "description" => "Un dolce croccante e goloso, preparato con mandorle tostate, zucchero e miele.",
                "price" => 8.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante italiano e indiano id 14
            [
                "restaurant_id" => 14,
                "name" => "Tagliatelle al Ragù",
                "description" => "Una ricetta della tradizione bolognese, con tagliatelle fatte in casa e condite con un saporito ragù di carne.",
                "price" => 18.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 14,
                "name" => "Pollo alla Cacciatora",
                "description" => "Un piatto tipico della cucina toscana, preparato con pollo, pomodori, olive, cipolla e peperoncino.",
                "price" => 19.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 14,
                "name" => "Filetto di Branzino al Cartoccio",
                "description" => "Un gustoso piatto di pesce, preparato con filetto di branzino fresco, verdure e spezie, cottura a vapore in carta forno.",
                "price" => 23.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            [
                "restaurant_id" => 14,
                "name" => "Insalata Caprese",
                "description" => "Un'insalata fresca e colorata, ideale come antipasto o contorno, con pomodori, mozzarella di bufala e basilico.",
                "price" => 10.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 14,
                "name" => "Tiramisù",
                "description" => "Un dolce italiano classico, preparato con savoiardi, caffè, mascarpone e cacao.",
                "price" => 7.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 14,
                "name" => "Panna Cotta",
                "description" => "Un dolce delicato e cremoso, preparato con panna, gelatina, zucchero e vaniglia.",
                "price" => 6.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 14,
                "name" => "Croccante alle Mandorle",
                "description" => "Un dolce croccante e goloso, preparato con mandorle tostate, zucchero e miele.",
                "price" => 8.00,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante cucina cinese e americana id 15
            [
                "restaurant_id" => 15,
                "name" => "Risotto alle erbe aromatiche",
                "description" => "Risotto carnaroli con erbe aromatiche fresche e formaggio grana grattugiato.",
                "price" => 12.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ], [
                "restaurant_id" => 15,
                "name" => "Lacca di maiale",
                "description" => "Maiale cotto lentamente in una lacca dolce e aromatico, servito con verdure saltate.",
                "price" => 16.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 15,
                "name" => "Zuppa di miso vegetale",
                "description" => "Zuppa di miso con cubetti di tofu, alghe e verdure di stagione, arricchita con salsa di soia e pasta di chili.",
                "price" => 8.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 15,
                "name" => "Gamberoni in salsa di zenzero e cipolla",
                "description" => "Gamberoni freschi scottati in padella con salsa di zenzero, cipolla e aglio, serviti con riso basmati.",
                "price" => 17.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 15,
                "name" => "Insalata di alghe",
                "description" => "Insalata di alghe wakame con cetrioli marinati, uova di quaglia e dressing di sesamo.",
                "price" => 7.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,

            ],
            [
                "restaurant_id" => 15,
                "name" => "Polpo arrosto con patate",
                "description" => "Polpo tenero arrosto al forno con patate e cipolla, servito con contorno di insalata mista.",
                "price" => 19.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 15,
                "name" => "Noodles di riso con verdure saltate",
                "description" => "Noodles di riso saltati con verdure miste, salsa di soia e salsa di ostriche.",
                "price" => 11.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante messicano e polacco id 16
            [
                "restaurant_id" => 16,
                "name" => "Enchiladas",
                "description" => "Tortilla di mais ripiena di carne di manzo o pollo e condita con salsa al pomodoro e peperoncino.",
                "price" => 10.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 16,
                "name" => "Quesadillas",
                "description" => "Tortilla di grano ripiena di formaggio fuso, fagioli e carne di maiale o pollo.",
                "price" => 8.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 16,
                "name" => "Fajitas",
                "description" => "Strisce di carne di manzo o pollo arrostito con peperoni, cipolle e spezie, serviti con tortilla di grano.",
                "price" => 12.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 16,
                "name" => "Ceviche",
                "description" => "Piatto di pesce crudo marinato con lime, peperoncino, coriandolo e cipolla rossa.",
                "price" => 11.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 16,
                "name" => "Tacos de Pescado",
                "description" => "Taco di pesce fritto, condito con cipolla, coriandolo e una salsa di peperoncino.",
                "price" => 9.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 16,
                "name" => "Huevos Rancheros",
                "description" => "Uova fritte servite con fagioli, salsa di pomodoro e peperoncino, avocado e tortilla di mais.",
                "price" => 7.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 16,
                "name" => "Guacamole",
                "description" => "Salsa cremosa di avocado, cipolla, pomodoro, coriandolo e lime, servita con tortilla chips.",
                "price" => 6.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,
            ],
            // Piatti ristorante americano e indiano id 17
            [
                "restaurant_id" => 17,
                "name" => "Cheeseburger",
                "description" => "Hamburger con formaggio fuso, servito con insalata, pomodoro e salse varie.",
                "price" => 13.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 17,
                "name" => "Pulled pork sandwich",
                "description" => "Panino con carne di maiale cotta a lungo, servita con salsa barbecue e salse varie.",
                "price" => 13.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 17,
                "name" => "Chili con carne",
                "description" => "Speziato chili di carne macinata con fagioli, pomodoro e peperoncino, servito con crostini di pane.",
                "price" => 10.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 17,
                "name" => "Philly cheesesteak",
                "description" => "Panino con carne di manzo tagliata sottilmente, formaggio fuso e cipolle servito su un panino morbido.",
                "price" => 15.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 17,
                "name" => "Pancakes",
                "description" => "Crepes dolci e soffici serviti con burro e sciroppo d'acero.",
                "price" => 8.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ],
            [
                "restaurant_id" => 17,
                "name" => "Eggs Benedict",
                "description" => "Due uova in camicia su due fette di bacon e pane tostato, il tutto coperto da una salsa olandese.",
                "price" => 11.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 17,
                "name" => "Cobb salad",
                "description" => "Insalata con pollo grigliato, pancetta, avocado, pomodoro, formaggio e uovo sodo, condita con una vinaigrette.",
                "price" => 14.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            // Piatti ristorante messicano e polacco id 18
            [
                "restaurant_id" => 18,
                "name" => "Kaczka z Jablkami",
                "description" => "Anatra glassata al miele e spezie, servita con mele caramellati.",
                "price" => 15.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 18,
                "name" => "Polskie Kotlety Mielone",
                "description" => "Polpette di carne macinata mista, servite con purea di patate e salsa di funghi.",
                "price" => 12.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 18,
                "name" => "Kulebiak",
                "description" => "Torta salata di pasta sfoglia ripiena di salmone, riso e verdure.",
                "price" => 14.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 18,
                "name" => "Placki ziemniaczane",
                "description" => "Frittelle di patate grattugiate, servite con panna acida e pancetta affumicata.",
                "price" => 8.95,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 18,
                "name" => "Sernik",
                "description" => "Torta di formaggio cremoso, servita con marmellata di frutti di bosco.",
                "price" => 6.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 18,
                "name" => "Kopytka",
                "description" => "Gnocchi di patate, serviti con salsa di carne e funghi.",
                "price" => 9.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 18,
                "name" => "Kurczak po żarsku",
                "description" => "Pollo arrosto alla polacca, condito con aglio, prezzemolo e paprika, servito con patate al forno.",
                "price" => 13.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ],
            // Ristorante indiano e cinese id 19    
            [
                "restaurant_id" => 19,
                "name" => "Samosa di verdure",
                "description" => "Fagottini di pasta ripieni di patate, piselli, carote, fagioli verdi e spezie, fritti croccanti e serviti con chutney.",
                "price" => 7.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,
            ], [
                "restaurant_id" => 19,
                "name" => "Kofta curry",
                "description" => "Polpette di verdure o di paneer (formaggio indiano) in una salsa cremosa di pomodoro e cipolla, servite con riso basmati o naan.",
                "price" => 12.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,
            ], [
                "restaurant_id" => 19,
                "name" => "Pakora di cipolle",
                "description" => "Fette di cipolla fritte in pastella di farina di ceci e spezie, servite con chutney.",
                "price" => 6.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 1,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 19,
                "name" => "Chicken tikka",
                "description" => "Petti di pollo marinati in spezie indiane e grigliati, serviti con una salsa di menta e coriandolo, riso basmati o naan.",
                "price" => 13.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 19,
                "name" => "Gulab jamun",
                "description" => "Palline dolci di latte condensato e farina di latte, fritte e inzuppate in uno sciroppo di zucchero, servite con gelato alla vaniglia.",
                "price" => 6.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            [
                "restaurant_id" => 19,
                "name" => "Raita",
                "description" => "Salsa di yogurt con cetrioli, menta e spezie, ottima per accompagnare piatti piccanti.",
                "price" => 4.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ], [
                "restaurant_id" => 19,
                "name" => "Saag paneer",
                "description" => "Spinaci cotti con spezie indiane e cubetti di paneer (formaggio indiano), serviti con riso basmati o naan.",
                "price" => 11.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,
            ],
            // Ristorante americano e giapponese id 20
            [
                "restaurant_id" => 20,
                "name" => "Okonomiyaki",
                "description" => "Pancake giapponese con ripieno di verdure, carne di maiale o gamberi, servito con salsa okonomiyaki e maionese.",
                "price" => 10.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ], [
                "restaurant_id" => 20,
                "name" => "Gyoza",
                "description" => "Ravioli ripieni di carne di maiale o verdure, cotti al vapore e poi dorati in padella, serviti con salsa di soia.",
                "price" => 8.75,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 20,
                "name" => "Tonkatsu",
                "description" => "Bistecca di maiale impanata e fritta, servita con riso e salsa tonkatsu.",
                "price" => 15.50,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ], [
                "restaurant_id" => 20,
                "name" => "Sukiyaki",
                "description" => "Stufato di carne, verdure, tofu e noodles in brodo di dashi e salsa di soia, cotto direttamente sulla tavola.",
                "price" => 22.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 1,

            ], [
                "restaurant_id" => 20,
                "name" => "Katsuobushi",
                "description" => "Pesce secco affumicato e affettato sottilmente, servito con salsa di soia e zenzero marinato.",
                "price" => 9.25,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 20,
                "name" => "Chirashi",
                "description" => "Piatto di pesce crudo su base di riso misto, servito con salsa di soia e wasabi.",
                "price" => 20.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,

            ],
            [
                "restaurant_id" => 20,
                "name" => "Tonjiru",
                "description" => "Zuppa a base di miso con cubetti di carne di maiale, radici e verdure.",
                "price" => 9.99,
                "quantity" => 0,
                "is_visible" => 1,
                "photo" => "",
                "is_vegan" => 0,
                "is_vegetarian" => 0,
            ]
        ];

        foreach ($plates as $plate) {
            $new_plate = new Plate();
            $new_plate->fill($plate);
            $new_plate->save();
        }
    }
}
